name: AdManage Tests

on:
  # Run on push to main branch
  push:
    branches: [ main ]
  # Run on pull requests
  pull_request:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:
  # Run on schedule (e.g., daily at 2 AM UTC)
  schedule:
    - cron: '0 2 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Run AdManage Tests
      id: run-tests
      run: |
        # Call the Railway server endpoint
        response=$(curl -s -w "\n%{http_code}" ${{ secrets.RAILWAY_SERVER_URL }}/run-admanage-tests)
        http_code=$(echo "$response" | tail -n1)
        body=$(echo "$response" | sed '$d')
        
        echo "HTTP Status Code: $http_code"
        echo "Response Body: $body"
        
        # Parse JSON response
        success=$(echo "$body" | jq -r '.success')
        message=$(echo "$body" | jq -r '.message')
        execution_time=$(echo "$body" | jq -r '.executionTime')
        passed_tests=$(echo "$body" | jq -r '.summary.passedTests')
        total_tests=$(echo "$body" | jq -r '.summary.totalImplementedTests')
        
        echo "Success: $success"
        echo "Message: $message"
        echo "Execution Time: ${execution_time}s"
        echo "Tests Passed: $passed_tests/$total_tests"
        
        # Set outputs for other steps
        echo "success=$success" >> $GITHUB_OUTPUT
        echo "message=$message" >> $GITHUB_OUTPUT
        echo "execution_time=$execution_time" >> $GITHUB_OUTPUT
        echo "test_summary=$passed_tests/$total_tests" >> $GITHUB_OUTPUT
        
        # Fail the job if tests failed
        if [ "$success" != "true" ]; then
          echo "❌ Tests failed!"
          echo "$body" | jq -r '.failureDetails // "No failure details available"'
          exit 1
        else
          echo "✅ All tests passed!"
        fi
    
    - name: Comment PR (if applicable)
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v6
      with:
        script: |
          const success = '${{ steps.run-tests.outputs.success }}' === 'true';
          const message = '${{ steps.run-tests.outputs.message }}';
          const executionTime = '${{ steps.run-tests.outputs.execution_time }}';
          const testSummary = '${{ steps.run-tests.outputs.test_summary }}';
          
          const emoji = success ? '✅' : '❌';
          const status = success ? 'passed' : 'failed';
          
          const comment = `${emoji} **AdManage Tests ${status}**
          
          - **Tests**: ${testSummary}
          - **Execution Time**: ${executionTime}s
          - **Message**: ${message}
          
          [View full test results](${{ secrets.RAILWAY_SERVER_URL }}/run-admanage-tests)`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
    
    - name: Create Test Report
      if: always()
      run: |
        # Create a summary for the workflow
        echo "## AdManage Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ "${{ steps.run-tests.outputs.success }}" = "true" ]; then
          echo "✅ **All tests passed!**" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Some tests failed**" >> $GITHUB_STEP_SUMMARY
        fi
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "- **Tests**: ${{ steps.run-tests.outputs.test_summary }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Execution Time**: ${{ steps.run-tests.outputs.execution_time }}s" >> $GITHUB_STEP_SUMMARY
        echo "- **Server**: ${{ secrets.RAILWAY_SERVER_URL }}" >> $GITHUB_STEP_SUMMARY